name: Link Check

on:
  push:
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
